### PR TITLE
Added automatic agent filter for execution to limit execution to nodes with agent installed

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ajf8** [comment]
Hey there,

Thank you for the patch, but I don't think it is necessary to explicitly set an agent filter on the rpcclient.

An rpcclient is created with the agent as an argument. If you follow from the rpcclient method in rpc.rb into rpc/client.rb you will see the call to agent_filter.

Please let me know if I'm missing something.

Thanks

**Comment by ghost** [comment]
When I was running an action across several servers where the agent was
installed on a subset of the servers, it would wait for the other servers
to timeout. MCO didn't have this behavior, so I looked at the code, and it
was using an implicit filter to only run the action on the servers with the
agent installed. I applied the same principle to the controller, and the
execution no longer times out for the servers that are missing the agent. I
guess the RPC client doesn't do this automatically.

**Comment by ghost** [comment]
Oh, I get it, you set a blank agent filter no matter what, that kills the
filter set in client. Rb

**Comment by ajf8** [comment]
Ah OK.. That makes sense then.

Thanks for testing, will merge

**Pull request merged**
