### PR TITLE
Vagrant support and cleanup

### PR DESCRIPTION
**Pull request by lmello**
run:
rake r10k:install  #install the puppet modules external dependencies
cd tools/vagrant  #go the vagrant directory
vagrant up  #start the vagrant definitions
vagrant ssh mcomaster  #enter in the mcomaster machine
mcomaster$mco ping  
mcomaster$sudo -s
# START mcomaster

mcomaster#RAILS_ENV=production scl enable ruby193 "/usr/share/mcomaster/bin/rails server -p 8080 "

Now open in your webbrowser http://localhost:8080, and can login using the username vagrant@example.com
password vagrant
You will have all three machines configured,
middleware (activemq and redis), mcserver (one
server to test mcollective) and mcomaster (the mcollective
client with mcomaster.

TODO:
Make sure the mcomaster puppet module provides a initscript
and configures the mcomaster service.
The idea is we could only run vagrant up and go to http://localhost:8080.

Probaly you will need to merge by hand because of the directory installer moved to tools/puppet/modules 
and directory  installer is a link.

### CODE REVIEW

**Comment by lmello** [comment]
it is not finished yet. so please don't merge. I created the merge request so you could test and give your opnion.

**Comment by lmello** [comment]
There is any chance to have rpm packages with the last fix of mcollective > 2.4 ?  
In this vagrant environment until we have the rpm packages updated, you will reproduce exactly the same issue that was fixed on my last pull request. 
:-D

**Comment by ajf8** [comment]
Hi, sure, there should be one there now. Just had to turn on my fileserver which runs jenkins :)

**Comment by lmello** [comment]
Thanks.

**Comment by lmello** [comment]
I had done, could you test it ? 

There is documentation on VAGRANT.MD!

Hope this would be usefull for the project, helping people testing and adoption. 

Thanks for your hard work on such a great tool. 

best 
Leo

**Comment by lmello** [comment]
@ajf8

**Comment by ajf8** [comment]
Looks good and very useful, I'll try using it for my own development. Thanks. I'm on a train right now so couldn't install Vagrant but I'll take a look when I get home.

**Comment by ajf8** [comment]
I tried this last night and I came really close to getting it going. It's excellent work, thank you, can't wait to use it... I tried vagrant a while ago on my laptop it didn't work so well, so I've just had a few KVM virtual machines until now.

I'll put a mention on the mcomaster.org site and README.md site once it's merged, it's really neat.

The mcollective puppet module wasn't installing, looks like it's because it uses the contain keyword which is quite a recent addition to puppet, but 3.1 was installed in the VMs.

I tried working around that by referencing the commit before the contain keyword was introduced, and then I had to manually change "package { $mcollective::client_package" to "package { $mcollective::client_package_name" so it matched the parameter names in init.pp. So I guess there's either an earlier commit which doesn't have that bug or we can upgrade the vagrant box 
or just puppet to be a later version (3.4 for the contain keyword?).

mod 'mcollective',
  :git => 'https://github.com/puppetlabs/puppetlabs-mcollective',
  :ref => '138271c'

After that I kept getting errors like this in the mcomaster VM mentioning different packages and yum repositories.

==> mcomaster: Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install mcollective-client' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: mcomaster. Please verify its path and try again

It looks like it's because those packages are trying to install before the firewall rules so it just needs a dependency adding, maybe something like Firewall<| |> -> Package<| |>. I'll investigate further tonight. :)

**Comment by lmello** [comment]
thanks for testing and feedback. 
I believe the problem could be related for me not using specific versions on Puppetfile. 
I am changing that will push a commit soon. 
Could you paste the output of the following commands : 

``` bash
cd tools/puppet/external-modules/ && for i in `ls `; do head -3  $i/metadata.json   | tail -2 ; done 
```

I will have more time to dig into that on sunday. :-D

**Comment by lmello** [comment]
discovered the problem... 
Mcollective module
Latest version: 2.0.0-rc0
Release date: Jul 23, 2014 
I was using 1.1.6 .. SemVer broken compatibility. :-D

**Comment by lmello** [comment]
could you test again ? 

I will have some spare time on sunday to finish anything that is missing. 

best 
Léo

**Comment by ajf8** [comment]
Yep that fixed the issue with the catalogue compile nicely. Was still getting some ordering issues with the firewall rules and package installs which I think I fixed with a require before merging. Let me know if you think there's a better way.

It works beautifully and does a really impressive job of setting everything up easily. Great work :) I'll be be using it and add a note to the existing docs and website about it soon.

**Pull request merged**
