### PR TITLE
fix images url in javascript and css.

### PR DESCRIPTION
**Pull request by lmello**
https://github.com/ajf8/mcomaster/issues/9.
This solves the asset problem for scss and javascript.

The issue is: https://github.com/ajf8/mcomaster/issues/9 .

### CODE REVIEW

**Comment by ajf8** [comment]
Excellent! I've been meaning to fix this issue for a while, many thanks for your contribution.

**Comment by lmello** [comment]
;). Thanks for merging. There is only onde Palace that i could not solve the template for search. Didn't figures how to solve it. Maybe This commits could help you figure how . maybe it would require a change to the search.

**Comment by lmello** [comment]
Onde = one
palace = place. 

Bad android robot.

**Comment by ajf8** [comment]
:) 

Yes I see the problem with that search_item template referenced in app/assets/javascripts/views/logged_in_bar.coffee

We only know the image name in javascript land but need to figure out the real image path beforehand in ruby... I'll try adding that onto the search_controller.rb response, should be fairly easy.

**Pull request merged**
